GUI
alexander-kurdakov/ProgrammingCourseSPbU1Year pull request #14
Opened 2021-11-01 18:35 UTC by alexander-kurdakov

GUI for Arithm.

2021-11-03 08:13 UTC, gsvgit commented on src/GUI/ViewModels/MainWindowViewModel.cs
> +        public string Greeting => "Welcome to Avalonia!";
А это точно надо?

2021-11-03 08:13 UTC, gsvgit commented on src/GUI/ViewModels/ViewModelBase.cs
> +    public class ViewModelBase : ReactiveObject
А это зачем?

2021-11-03 08:13 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            _consoleBox.Text = "Execution started:\n";
Раз уж сообщаете, что выполнение начато, сообщайте явно и когда оно закончено.

2021-11-03 08:13 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
А как у Вас обрабатываются ошибки синтаксического анализа и интерпретации?

2021-11-03 09:09 UTC, alexander-kurdakov commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
Так чуть чуть ниже же.

2021-11-03 09:12 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
Если я правильно понимаю, то чуть ниже это обработка исключений, возникших при печати.

2021-11-03 09:31 UTC, alexander-kurdakov commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
почему при печате? если написать 
let x = 5~ 
он выдаст ошибку синтаксического анализа

2021-11-03 09:38 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
А как так получается? У Вас же в try это всё не завёрнуто.

2021-11-03 10:01 UTC, alexander-kurdakov commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
Если при выполнении таски вылетело исключение, то при обращении к t.Result мы его поймаем. Исключение не может быть не пойманым.

2021-11-03 10:20 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
Исключение как раз может быть не пойманным. Но ок, пусть будет так)

2021-11-08 08:40 UTC, gsvgit requested changes

2021-11-08 08:40 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
Я правильно понимаю, что Вы сперва накопите весь результат, а потом массово напечататее его в консоль? Можно ли как-то сдалть так, чтобы результат печатался по мере появления.

2021-11-08 08:40 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            Save(sender, e);
Воу. А вот редактировал я что-то редактировал, нажал "New" и потерял всё, что писал до этого.

2021-11-08 08:40 UTC, gsvgit commented on src/GUI/Views/MainWindow.axaml.cs
> +            var openedFileDialog = new OpenFileDialog();
Что-тр ир мне кажется, что при нажатии Open тоже потеряю всё, что писал до этого.

2021-11-08 10:36 UTC, alexander-kurdakov commented on src/GUI/Views/MainWindow.axaml.cs
> +            Save(sender, e);
Кажется, что это неправда =)

2021-11-08 10:39 UTC, alexander-kurdakov commented on src/GUI/Views/MainWindow.axaml.cs
> +            var openedFileDialog = new OpenFileDialog();
Исправил.

2021-11-08 21:47 UTC, alexander-kurdakov commented on src/GUI/Views/MainWindow.axaml.cs
> +            var task = new Task<string>(() => Interpreter.runPrint(Interpreter.parse(code)));
Сделал.

2021-11-09 06:46 UTC, gsvgit commented
1. Запускаю IDE, набираю код, говорю "сохранить", ввожу имя файла. Всё хорошо. Модифицирую код и хочу сохранить. Зачем-то снова просит имя файла. Зачем?
2. А сможете сделать так, чтобы стандартные сочетания типа Ctrl+S, Ctrl+O работали?

2021-11-09 20:48 UTC, alexander-kurdakov commented
>     1. Запускаю IDE, набираю код, говорю "сохранить", ввожу имя файла. Всё хорошо. Модифицирую код и хочу сохранить. Зачем-то снова просит имя файла. Зачем?
> 
>     2. А сможете сделать так, чтобы стандартные сочетания типа Ctrl+S, Ctrl+O работали?

Сделал.

2021-11-11 08:42 UTC, gsvgit approved these changes
Пусть будет так.

2021-11-18 17:30 UTC, merged