part of ATM Library
alexander-kurdakov/ProgrammingCourseSPbU1Year pull request #9
Opened 2021-04-03 19:08 UTC by alexander-kurdakov

NFA transitions based on quadTrees

2021-04-06 05:48 UTC, gsvgit requested changes
1) Плохо, что Вы постоянно гоняете матрицы из одного представления в другое.
2) Не нашёл нормальных тестов на автоматы.

2021-04-06 05:48 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +            Array2D.init
Смотрите, что получается. Из-за того, что Вы не совсем честно сделали матрицы на деревьях, Вам с ними не очень удобно работать. В результате, Вы сперва создаёте честный двумерный массив, выделяете под него кучу памяти, работаете с ним, а потом превращаете в разреженное представление. Это плохой подход. Если вам чего-то не хватает в разреженном представлении --- улучшите его.

2021-04-06 05:48 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +        let mtx = Array2D.init (input.Length + 1) (input.Length + 1) (fun _ _ -> HashSet())
И снова. А если строка огромная? Сколько лишней памяти Вы выделили.

2021-04-06 05:48 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +    let eCls2D = treeToArray2DHash eCls
А зачем опять гонять из одного представления в другое?

2021-04-20 11:20 UTC, gsvgit requested changes
Но уже лучше, конечно.

2021-04-20 11:20 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +        let r = if s1.IsEmpty then Set.empty<NFASmb<'t>> else Set<NFASmb<'t>>(s1)
Их правда нельзя просто взять и объединить?

2021-04-20 11:20 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +    Set(r)
А зачем Вам то Set, то HashSet?

2021-04-20 11:20 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +    let sparse = SparseMatrix(input.Length + 1, input.Length + 1, makeLst input 0 [])
Больше, больше преобразования между разными типами матриц!

2021-04-20 11:20 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +    let header =
И вот мы снова подобрались к использованию интерфейсов)

2021-04-20 11:20 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +    let resTree = extendedTree.createTreeOfSparseMatrix algStrForSetsOp
Ещё больше преобразований!

2021-04-20 13:56 UTC, alexander-kurdakov commented on src/ATMLibrary/TreeNFA.fs
> +    Set(r)
деревеья не могут отлавливать нейтральный элемент(пустой ХэшСет)

2021-04-20 14:04 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +    Set(r)
Думается, деревья тут не при чём.

2021-04-20 21:40 UTC, alexander-kurdakov commented on src/ATMLibrary/TreeNFA.fs
> +    let sparse = SparseMatrix(input.Length + 1, input.Length + 1, makeLst input 0 [])
не совсем понял что Вы имеете в виду. Нужно ввести индексация на деревьях?

2021-04-21 04:13 UTC, gsvgit commented on src/ATMLibrary/TreeNFA.fs
> +    let sparse = SparseMatrix(input.Length + 1, input.Length + 1, makeLst input 0 [])
Надо на деревьях сделать нормальные матрицы, да.

2021-04-27 12:50 UTC, gsvgit requested changes

2021-04-27 12:50 UTC, gsvgit commented on src/ATMLibrary/NFA.fs
> +    let header =
Что-то мне подсказывает, что пришла пора применять то, что сегодня на паре обсуждали. И для автоматов и для матриц.

2021-04-27 18:55 UTC, alexander-kurdakov commented on src/ATMLibrary/NFA.fs
> +    let header =
Да. Не успел отменить реквест.

2021-09-28 08:59 UTC, gsvgit requested changes
Разделите два реквеста, пожалуйста.

2021-09-28 08:59 UTC, gsvgit commented on src/eighthHomework/QuadTree.fs
>  open AlgebraicStructure
А это точно автоматы?

2021-09-28 14:56 UTC, alexander-kurdakov commented on src/eighthHomework/QuadTree.fs
>  open AlgebraicStructure
в это файле реализация квадродеревьями интерфейса IMatrix, на котором работает автомат. Это точно нужно в отдельный пул реквест оформлять?

2021-11-18 17:32 UTC, merged